name: on tags release-web
on:
  push:
    tags:
      - release-web

jobs:
  deploy:
    name: deploy on tags release-web
    runs-on: ubuntu-latest
    steps:
      - name: provision runner
        run: sudo apt-get install -y expect
      - name: add github hosts to known_host
        run: |
          mkdir ~/.ssh/ && touch ~/.ssh/known_hosts && \
            ssh-keyscan ${{ secrets.WAYF0000_LINODE_APSOUTH_0001_SSH_HOST }} >> ~/.ssh/known_hosts
      - name: executing remote ssh commands using password
        # make sure to escape the "$" if present in the password.
        # see: https://stackoverflow.com/questions/24373449/escape-in-expect-script
        # see: https://stackoverflow.com/questions/2871181/replacing-some-characters-in-a-string-with-another-character
        run: |
          WAYF0000_LINODE_APSOUTH_0001_SSH_PASSWD_ESCAPED="${{ secrets.WAYF0000_LINODE_APSOUTH_0001_SSH_PASSWD }}" | tr $ \\\$
          expect -c 'spawn ssh ${{ secrets.WAYF0000_LINODE_APSOUTH_0001_SSH_USER }}@${{ secrets.WAYF0000_LINODE_APSOUTH_0001_SSH_HOST }} \
            "whoami"; \
            expect "assword:"; send "$WAYF0000_LINODE_APSOUTH_0001_SSH_PASSWD_ESCAPED\r";'
