name: on tags release-web
on:
  push:
    tags:
      - release-web

jobs:
  deploy:
    name: deploy on tags release-web
    runs-on: ubuntu-latest
    steps:
      - name: provision runner
        run: sudo apt-get install -y expect
      - name: add github hosts to known_host
        run: |
          mkdir ~/.ssh/ && touch ~/.ssh/known_hosts && \
            ssh-keyscan ${{ secrets.WAYF0000_LINODE_APSOUTH_0001_SSH_HOST }} >> ~/.ssh/known_hosts
      - name: executing remote ssh commands using password
        run: |
          expect -c 'spawn ssh ${{ secrets.WAYF0000_LINODE_APSOUTH_0001_SSH_USER }}@${{ secrets.WAYF0000_LINODE_APSOUTH_0001_SSH_HOST }} \
            "whoami"; \
            expect "assword:"; send "${{ secrets.WAYF0000_LINODE_APSOUTH_0001_SSH_PASSWD }}\r";'
